site: Buster's Notes
url: https://notes.busterbenson.com
title: Buster's Notes
description: Notes
permalink: pretty

strict_front_matter: true
liquid:
  error_mode: strict
  
baseurl: ""

highlighter: none

exclude:
  - '.jekyll-cache'
  - 'Gemfile'
  - 'Gemfile.lock'
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style:    :compressed

kramdown:
  html_to_native: true

target-blank:
  add_css_classes: external-link

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jekyll-srcset
  - jekyll-youtube
  - jekyll-email-protect
  - jekyll-redirect-from

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  mood:
    output: false # Disabled for now
    permalink: /mood/:name
  tarot:
    output: true
    permalink: /tarot/:name
  symbol:
    output: true
    permalink: /symbol/:symbol

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope: 
      path: ""
      type: "pages"
    values:
      layout: "mood"
  - scope: 
      path: ""
      type: "pages"
    values:
      layout: "tarot"